import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ContextWrapper } from "@/contexts/wrapper.context";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";
import Header from "@/components/common/header";

const PoppinsFont = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${PoppinsFont.variable}  antialiased`}>
        <Toaster position="top-right" duration={4000} />
        <ContextWrapper>
          <Header />
          {children}
        </ContextWrapper>
      </body>
    </html>
  );
}
